# Generated by Django 5.1.2 on 2024-10-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_collegestudent_educationorganization_highstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='class_rooms',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='college',
            name='masters',
            field=models.ManyToManyField(to='school.master'),
        ),
        migrations.AlterField(
            model_name='college',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='elementary',
            name='class_room',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='elementary',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='elementary',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='firsthigh',
            name='class_room',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='firsthigh',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='firsthigh',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='class_room',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher'),
        ),
    ]
