# Generated by Django 5.1.2 on 2024-10-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_college_class_rooms_alter_college_masters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='student_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='salary_per_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='working_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary_per_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='working_days',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
