# Generated by Django 5.1.2 on 2024-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_collegestudent_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='grade',
            field=models.CharField(choices=[('lisans', 'lisans'), ('fogh lisans', 'fogh lisans'), ('doktora', 'doktora'), ('fogh doktora', 'fogh doktora')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='major',
            field=models.CharField(choices=[('Riazi', 'Riazi'), ('Ensani', 'Ensani'), ('tajrobi', 'tajrobi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='education_type',
            field=models.CharField(choices=[('shabane', 'shabane'), ('roozane', 'roozane'), ('pardis khod gardan', 'pardis khod gardan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collegestudent',
            name='sub_major',
            field=models.CharField(choices=[('bargh', 'bargh'), ('Software Engineering', 'Software Engineering'), ('mohandesi polimer', 'mohandesi polimer'), ('Computer Science', 'Computer Science')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='highstudent',
            name='major',
            field=models.CharField(choices=[('Riazi', 'Riazi'), ('Ensani', 'Ensani'), ('tajrobi', 'tajrobi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='secondhigh',
            name='major',
            field=models.CharField(choices=[('Riazi', 'Riazi'), ('Ensani', 'Ensani'), ('tajrobi', 'tajrobi')], max_length=20, null=True),
        ),
    ]
